app/__init__.py
"""
Application Flask et portail web serveur de rapport
"""


from flask import Flask, render_template
from werkzeug.wsgi import DispatcherMiddleware

import os, sys
# add to sys.path relative to the current running script
sys.path.append(os.path.join(os.path.dirname(__file__), ""))
# add the parent-parent directory
sys.path.append('../..')

from views import general
from common.common import common
from reports.demo.F01_hello_world.app import app as F01_hello_world
from reports.demo.F02_simple_app.app import app as F02_simple_app
from reports.demo.F03_complex_app.app import app as F03_complex_app
from reports.demo.D01_simple_app.app import app as D01_simple_app
from reports.demo.D02_simple_graphique.app import app as D02_simple_graphique
#from reports.demo.D03_dashboard_sklearn.app import app as D03_dashboard_sklearn

app = Flask(__name__, template_folder='templates')

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from report_server.app.views import general 
app.register_blueprint(general.mod)

dispatcher = DispatcherMiddleware(app, {
    '/common': common,   
    '/demo/F01_hello_world': F01_hello_world,  
    '/demo/F02_simple_app': F02_simple_app,  
  	'/demo/F03_complex_app': F03_complex_app,  
    '/demo/D01_simple_app': D01_simple_app.server,  
    '/demo/D02_simple_graphique': D02_simple_graphique.server,   
    #'/demo/D03_dashboard_sklearn': D03_dashboard_sklearn.server,  
})

app/views/general.py
# app/views/general.py

from flask import Flask, request, url_for, redirect, Blueprint, render_template

mod = Blueprint('general', __name__)

@mod.route('/')
def index():
    return render_template('general/index.html')

@mod.route('/cool_form', methods=['GET', 'POST'])
def cool_form():
    if request.method == 'POST':
        # do stuff when the form is submitted

        # redirect to end the POST handling
        # the redirect can be to the same route or somewhere else
        return redirect(url_for('general.index'))

    # show the form, it wasn't submitted
    return render_template('general/cool_form.html')

app/templates/general/cool_form.html
{% extends "layout.html" %}
{% block body %}

	<div class="container" style="padding-top: 20px">
	  <form method="post">
	      <button  class="btn btn-primary" type="submit">Do it!</button>
	  </form>
	</div>

{% endblock %}

app/templates/general/index.html
{% extends "layout.html" %}
{% block body %}

	<div class="container" style="padding-top: 20px">
		<div>
			<h1>Portail Python de Rapports</h1>
			<p>Le portail de rapport est une application Flask distincte des rapports et tableaux de bord.<br>
	    	<ul>
		    	<li><a href="{{ url_for('general.cool_form') }}">Lien propre au portail de rapports!</a></li>
		    </ul>
		  </p>
  	</div>

  	<br>
    <div class="card bg-light mb-12">
		  <div class="card-header"><h3>Rapports</h3></div>
		  <div class="card-body">
		    <h5 class="card-title">Applications Dash</h5>
		    <p class="card-text">
		    	<ul>
		    		<li><a href="./demo/D01_simple_app">Dash app n°1: Hello World!</a></li>
		    		<li><a href="./demo/D02_simple_graphique">Dash app n°2: Simple graphique</a></li>
		    		<!--<li><a href="./demo/D03_dashboard_sklearn">Dash app n°3: Dashboard Scikit-Learn</a></li>-->
		    	</ul>
    		</p>
		    <h5 class="card-title">Applications Flask</h5>
		    <p class="card-text">
		    	<ul>
		    		<li><a href="./demo/F01_hello_world">Fask app n°1: Hello World!</a></li>
		    		<li><a href="./demo/F02_simple_app">Fask app n°2: Simple application</a></li>
		    		<li><a href="./demo/F03_complex_app">Fask app n°3: Complexe application</a></li>
		    	</ul>
    		</p>
		  </div>
		</div>

  </div>

{% endblock %}

app/templates/layout.html
<!doctype html>
{% block head %}
<title>Serveur de rapport</title>
<meta charset=utf-8>
<link rel= "stylesheet" type= "text/css" href= "common/static/css/bootstrap.min.css">
<link rel="shortcut icon" href="{{ url_for('static', filename='img/siop.ico') }}">

{% endblock %}
<div class=box>
  
  {% block body %}{% endblock %}
  
</div>